improve Open GL ES2 spec conformance, to satisfy WebGL
When cross-compiling to emscripten, I get the following error
message in browser console, and no textures are displayed:

Error: WebGL: A texture is going to be rendered as if it were black,
as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D
texture, with a minification filter not requiring a mipmap, with its
width or height not a power of two, and with a wrap mode different
from CLAMP_TO_EDGE.

To fix it, we try to make sure that when CEGUI creates a new
opengl texture, it sets the min/mag filter to GL_LINEAR and the
texture wrap mode to GL_CLAMP always.

--HG--
branch : webgl_support